# Generated by Django 3.2.9 on 2021-11-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='products_img')),
                ('slug' ,models.SlugField(unique=True, db_index=True)),
                ('total_units', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
