# Generated by Django 3.2.9 on 2021-11-22 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_orderd',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Shipping_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shippingAddress', models.CharField(max_length=350)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order')),
            ],
        ),
    ]
